[data]
shandalar_dataset = "shandalar_2016"

[io]
encoding_scan_mode = "auto"

[logging]
preview_limit = 5
overwrite = true

[format_builder]
format_config_file_name = "custom_format"
output_format_type = "extended"

[deck_converter]