[data]
shandalar_card_pool = "shandalar_2016"

[io]
encoding_scan = "auto"

[logging]
preview_limit = 5
overwrite = true

[format_generator]
input_format_file = "custom_format"
output_format_type = "extended"

[deck_translator]