editions = [
    "Ninth Edition",
    "Revised Edition",
    "Fourth Edition",
    "Ice Age",
    "Homelands",
    "Alliances",
    "Time Spiral",
    "Coldsnap",
    "Fallen Empires",
    "The Dark",
    "Ninth Edition"
]

additional_bans = [
    # bugged
    "Primal Clay",
    "Cave People",
    "Hecatomb",
    "Errand of Duty",

    # offensive
    "Crusade",

    # lore-breaking
    "Kami of Old Stone",
    "Paladin en-Vec",
    "Battle of Wits",
    "Counsel of the Soratami",
    "Lumengrid Warden",
    "Rewind",
    "Wanderguard Sentry",
    "Death Pits of Rath",
    "Megrim",
    "Nantuko Husk",
    "Flowstone Crusher",
    "Flowstone Shambler",
    "Flowstone Slide",
    "Furnace of Rath",
    "Mogg Sentry",
    "Rathi Dragon",
    "Rogue Kavu",
    "Viashino Sandstalker",
    "King Cheetah",
    "Kavu Climber",
    "Zodiac Monkey",
    "Loxodon Warhammer",
    "Thran Golem",
    "Vulshok Morningstar",
    "Amrou Scout",
    "Ashcoat Bear",
    "Aspect of Mongoose",
    "Barbed Shocker",
    "Basalt Gargoyle",
    "Benalish Cavalry",
    "Bewilder",
    "Blazing Blade Askari",
    "Bogardan Hellkite",
    "Bogardan Rager",
    "Bonesplitter Sliver",
    "Call to the Netherworld",
    "Cavalry Master",
    "Dark Withering",
    "Draining Whelk",
    "Dralnu, Lich Lord",
    "Drifter il-Dal",
    "Drudge Reavers",
    "Faceless Devourer",
    "Feebleness",
    "Firemaw Kavu",
    "Flamecore Elemental",
    "Flowstone Channeler",
    "Foriysian Interceptor",
    "Fury Sliver",
    "Ghostflame Sliver",
    "Gorgon Recluse",
    "Griffin Guide",
    "Harmonic Sliver",
    "Havenwood Wurm",
    "Ith, High Arcanist",
    "Jaya Ballard, Task Mage",
    "Kaervek the Merciless",
    "Looter il-Kor",
    "Mangara of Corondar",
    "Might of Old Krosa",
    "Might Sliver",
    "Mogg War Marshal",
    "Mwonvuli Acid-Moss",
    "Ophidian Eye",
    "Pentarch Paladin",
    "Penumbra Spider",
    "Plague Sliver",
    "Pull from Eternity",
    "Scryb Ranger",
    "Shadow Sliver",
    "Sidewinder Sliver",
    "Skittering Monstrosity",
    "Spike Tiller",
    "Spiketail Drakeling",
    "Spinneret Sliver",
    "Stonebrow, Krosan Hero",
    "Stronghold Overseer",
    "Subterranean Shambler",
    "Tectonic Fiend",
    "Teferi, Mage of Zhalfir",
    "Temporal Isolation",
    "Trespasser il-Vec",
    "Undying Rage",
    "Unyaro Bees",
    "Venser's Sliver",
    "Viashino Bladescout",
    "Watcher Sliver",

    # unhealthy
    "Contract from Below",
    "Island Sanctuary",
    "Worship",
    "Magus of the Mirror",
    "Rebirth",
    "Form of the Dragon",
    "Biorhythm",

    #test
    "typo sliver",
    "oops this card doesn't exist"
]

additional_cards = [
    "Ancestral Recall",
    "Black Lotus",
    "Mox Emerald",
    "Mox Jet",
    "Mox Pearl",
    "Mox Ruby",
    "Mox Sapphire",
    "Timetwister",
    "Time Walk"    
]